[32mINFO    [0m juju.model:model.py:2087 Deploying ch:amd64/focal/indico-169
[32mINFO    [0m juju.model:model.py:2087 Deploying ch:amd64/focal/redis-k8s-7
[32mINFO    [0m juju.model:model.py:2087 Deploying ch:amd64/focal/redis-k8s-7
[33mWARNING [0m juju.model:model.py:1553 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1553 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:2947 Waiting for model:
  indico/0 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:model.py:2947 Waiting for model:
  indico/0 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:model.py:2947 Waiting for model:
  indico/0 [idle] waiting: Waiting for database availability
[32mINFO    [0m integration.new_relations.test_new_relations:test_new_relations.py:693 Verifying that the charm doesn't block when the extensions are enabled
[32mINFO    [0m juju.model:model.py:2947 Waiting for model:
  database/0 [executing] active: Primary
  database/1 [idle] active: 
  database/2 [idle] active: 
[33mWARNING [0m juju.model:model.py:1553 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:2947 Waiting for model:
  database/0 [idle] active: Primary
  database/1 [idle] active: 
  database/2 [idle] active: 
  indico/0 [executing] waiting: Waiting for database availability
[32mINFO    [0m juju.model:model.py:2947 Waiting for model:
  indico/0 [idle] waiting: Waiting for pebble
[32mINFO    [0m juju.model:model.py:2947 Waiting for model:
  indico/0 [idle] waiting: Waiting for pebble
[32mINFO    [0m juju.model:model.py:2947 Waiting for model:
  indico/0 [idle] waiting: Waiting for pebble
[32mINFO    [0m juju.model:model.py:2947 Waiting for model:
  indico/0 [idle] waiting: Waiting for pebble
[32mINFO    [0m juju.model:model.py:2947 Waiting for model:
  indico/0 [idle] waiting: Waiting for pebble
[32mINFO    [0m juju.model:model.py:2947 Waiting for model:
  indico/0 [idle] waiting: Waiting for pebble
[32mINFO    [0m juju.model:model.py:2947 Waiting for model:
  indico/0 [executing] maintenance: Starting indico-nginx container
[32mINFO    [0m pytest_operator.plugin:plugin.py:784 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.1.7    unsupported  02:05:47Z

App                      Version               Status   Scale  Charm                Channel        Rev  Address         Exposed  Message
another-application                            active       1  postgresql-test-app  edge            50  10.152.183.33   no       received database credentials of the first database
another-data-integrator                        waiting      1  data-integrator      latest/stable   13  10.152.183.50   no       installing agent
another-database         14.10                 active       3  postgresql-k8s                        1  10.152.183.130  no       Primary
data-integrator                                waiting      1  data-integrator      latest/stable   13  10.152.183.243  no       installing agent
database                 14.10                 active       3  postgresql-k8s                        0  10.152.183.89   no       Primary
indico                   3.2.8                 active       1  indico               stable         169  10.152.183.183  no       
other-discourse-k8s      3.1.3                 active       1  discourse-k8s        latest/stable   82  10.152.183.170  no       
postgresql-test-app                            active       2  postgresql-test-app  edge            50  10.152.183.94   no       received database credentials of the first database
redis-broker             ubuntu/redis@691f315  active       1  redis-k8s            stable           7                  no       
redis-cache              ubuntu/redis@691f315  active       1  redis-k8s            stable           7                  no       
redis-k8s                7.0.4                 active       1  redis-k8s            latest/edge     27  10.152.183.252  no       

Unit                        Workload  Agent  Address      Ports     Message
another-application/0*      active    idle   10.1.137.22            received database credentials of the first database
another-data-integrator/0*  blocked   idle   10.1.137.26            Please relate the data-integrator with the desired product
another-database/0*         active    idle   10.1.137.19            Primary
another-database/1          active    idle   10.1.137.21            
another-database/2          active    idle   10.1.137.20            
data-integrator/0*          blocked   idle   10.1.137.25            Please relate the data-integrator with the desired product
database/0*                 active    idle   10.1.137.15            Primary
database/1                  active    idle   10.1.137.24            
database/2                  active    idle   10.1.137.23            
indico/0*                   active    idle   10.1.137.34            
other-discourse-k8s/0*      active    idle   10.1.137.30            
postgresql-test-app/0*      active    idle   10.1.137.8             received database credentials of the first database
postgresql-test-app/1       active    idle   10.1.137.9             received database credentials of the first database
redis-broker/0*             active    idle   10.1.137.35  6379/TCP  
redis-cache/0*              active    idle   10.1.137.37  6379/TCP  
redis-k8s/0*                active    idle   10.1.137.29            

[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Juju error logs:

unit-database-0: 01:43:21 ERROR unit.database/0.juju-log database:20: Invalid extra user roles: test
unit-database-0: 01:43:21 ERROR unit.database/0.juju-log database:20: invalid role(s) for extra user roles
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-0/charm/src/relations/postgresql_provider.py", line 90, in _on_database_requested
    self.charm.postgresql.create_user(user, password, extra_user_roles=extra_user_roles)
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 221, in create_user
    raise PostgreSQLCreateUserError(INVALID_EXTRA_USER_ROLE_BLOCKING_MESSAGE)
charms.postgresql_k8s.v0.postgresql.PostgreSQLCreateUserError: invalid role(s) for extra user roles
unit-database-0: 01:43:24 ERROR unit.database/0.juju-log database:21: Invalid extra user roles: test
unit-database-0: 01:43:24 ERROR unit.database/0.juju-log database:21: invalid role(s) for extra user roles
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-0/charm/src/relations/postgresql_provider.py", line 90, in _on_database_requested
    self.charm.postgresql.create_user(user, password, extra_user_roles=extra_user_roles)
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 221, in create_user
    raise PostgreSQLCreateUserError(INVALID_EXTRA_USER_ROLE_BLOCKING_MESSAGE)
charms.postgresql_k8s.v0.postgresql.PostgreSQLCreateUserError: invalid role(s) for extra user roles
unit-redis-k8s-0: 01:45:09 ERROR unit.redis-k8s/0.juju-log redis-peers:23: Error when connecting to sentinel: Error 111 connecting to 0.0.0.0:26379. Connection refused.
unit-redis-k8s-0: 01:45:09 ERROR unit.redis-k8s/0.juju-log redis-peers:23: Unit redis-k8s/0 doesn't agree on tracked master
unit-redis-k8s-0: 01:45:09 ERROR unit.redis-k8s/0.juju-log redis-peers:23: Error when connecting to sentinel: Error 111 connecting to localhost:26379. Connection refused.

[32mINFO    [0m pytest_operator.plugin:plugin.py:856 Forgetting main...